version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/droid-builder:latest
    environment:
      MANIFEST_BRANCH: 'android-9.0'
      # PBRP_BRANCH: 'android-9.0'
      VERSION: '3.0.0'
      VENDOR: 'xiaomi'
      CODENAME: 'tulip'
      BUILD_LUNCH: 'omni_tulip-eng'
      # It's either Official build or Test build
      # PB_OFFICIAL: 'true'
      TEST_BUILD: 'true'
      # EXTRA_CMD: ''
      CHANGELOG: |
        - Bringup 3.0 
        - Source side changes 
        - Fully Redesigned UI 
        - New Android like Power Menu (Activated via power key hold) 
        - Flashlight toggled by Vol up(+) on hold 
        - Flashlight toggle on Lockscreen 
        - Etc.
    working_directory: /home/builder/pitchblack
    steps:
      - run:
          name: AIO Build
          command: |
            echo "Set GitAuth Infos"
            git config --global user.email $GitHubMail
            git config --global user.name $GitHubName
            git config --global color.ui true
            wget -q https://raw.githubusercontent.com/PitchBlackRecoveryProject/vendor_utils/pb/build.sh
            source build.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: org-global
          filters:
            branches:
              only: 'android-9.0'
